version: '3'
services:
  cuckoo-mongo:
    image: mongo
    volumes:
      - DOCKER_MONGO_DIR/db:/data/db
      - DOCKER_MONGO_DIR/etc/mongod.conf:/etc/mongod.conf
    networks:
      phoenix:
        ipv4_address: DOCKER_MONGO_IP
    ports:
      - "27017:27107"
    restart: always
  cuckoo-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - DOCKER_ELASTIC_DIR:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    restart: always
    networks:
      phoenix:
        ipv4_address: DOCKER_ELASTIC_IP
  cuckoo-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=CUCKOO_USER
      - MYSQL_PASSWORD=DOCKER_MYSQL_PASSWORD
      - MYSQL_DATABASE=DOCKER_MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=DOCKER_MYSQL_ROOT_PASSWORD
    volumes:
      - DOCKER_MYSQL_DIR:/var/lib/mysql
    networks:
      phoenix:
        ipv4_address: DOCKER_MYSQL_IP
    restart: always
networks:
  phoenix:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: DOCKER_MONGO_NET